fudousan/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('koukoku.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.urls import path, include

from users.views import RegisterView, ProfileUpdateView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('<int:pk>/', ProfileUpdateView.as_view(), name='user_profile_update'),
    path('register/', RegisterView.as_view(), name='register'),
    url('social-auth/', include('social_django.urls', namespace='social')),
]

koukoku/models.py
from django.db import models
from django.conf import settings

class Region(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название области")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Область"
        verbose_name_plural = "Области"


class City(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название города")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Город"
        verbose_name_plural = "Города"


class District(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название района")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Район"
        verbose_name_plural = "Районы"


class Location(models.Model):
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, verbose_name="Город")
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True, verbose_name="Район")
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, verbose_name="Область")

    def __str__(self):
        return f"{self.region} - {self.city} - {self.district}"

    class Meta:
        verbose_name_plural = "Локации"


class Communication(models.Model):
    name = models.CharField(max_length=100, verbose_name="Коммуникации")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Коммуникации"


class Document(models.Model):
    name = models.CharField(max_length=100, verbose_name="Документы")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Документы"


class TargetPurpose(models.Model):
    name = models.CharField(max_length=100, verbose_name="Целовое назначение")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Целовое назначение"


class Infrastructure(models.Model):
    name = models.CharField(max_length=100, verbose_name="Инфраструктура")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Инфраструктура"


class Image(models.Model):
    image = models.ImageField(verbose_name="Изображение")
    estate = models.ForeignKey('Estate', on_delete=models.CASCADE, related_name='images', null=True,
                               verbose_name='Объявление')

    def __str__(self):
        return f"{self.estate}"

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"


class Estate(models.Model):

    CURRENCY_CHOICES = (
        ("1", "USD"),
        ("2", "СОМ"),
        ("3", "Договорная"),
    )

    DEAL_TYPE_CHOICES = (
        ("1", "Продаю участок"),
        ("2", "Продаю дом"),
        ("3", "Продаю под снос"),
        ("4", "Аренда участка"),
        ("5", "Куплю участок/дом"),
    )

    name = models.CharField(max_length=50, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    # image = models.ImageField(verbose_name="Изображение")
    # images = models.ManyToManyField(Image, related_name='estate_images', null=True, verbose_name="Изображения")
    plot_area = models.PositiveSmallIntegerField(null=True, verbose_name="Площадь участка сот.")
    house_area = models.PositiveSmallIntegerField(null=True, verbose_name="Площадь дома КВ.М")
    deal_type = models.CharField(max_length=30, choices=DEAL_TYPE_CHOICES, default=None, verbose_name="Тип сделки")
    price = models.PositiveIntegerField(null=True, verbose_name="Цена")
    currency = models.CharField(max_length=20, choices=CURRENCY_CHOICES, default=None, verbose_name="Валюта")
    phone = models.CharField(max_length=10, verbose_name="Номер телефона")
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, verbose_name="Расположение")
    target = models.ForeignKey(TargetPurpose, on_delete=models.SET_NULL, null=True, verbose_name="Целевое назначение")
    communications = models.ManyToManyField(Communication, null=True, verbose_name="Коммуникации")
    documents = models.ForeignKey(Document, on_delete=models.SET_NULL, null=True, verbose_name="Документы")
    infrastructure = models.ManyToManyField(Infrastructure, null=True,
                                       verbose_name="Инфраструктура")

    def __str__(self):
        return f"Объявление: {self.name}"

    class Meta:
        verbose_name_plural = "Объявления"



# class FavoriteItem(models.Model):
#     owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Пользователь")
#     estate = models.ForeignKey(Estate, on_delete=models.CASCADE, verbose_name='Объявление')

templates/base.html
{% load static %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <title>Fudousan</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/logo.svg' %}">
    </head>
    <body class="container">
    <nav class="navbar bg-light">
  <div class="container-fluid">
      <ul class="nav nav-pills">
              <a class="navbar-brand" aria-current="page" href="{% url 'estate_list' %}">
                  <img src="{% static 'images/logo.svg' %}" alt="" width="50" height="40" class="d-inline-block align-text-top" >Fudousan
              </a>
      </ul>

      <ul class="nav justify-content-end">
      <li class="nav-link active">
          <a class="btn btn-warning" href="{% url 'estate_create' %}">Добавить объявление</a>
          </li>
              {% if user.is_authenticated %}
                   <a class="nav-link d-flex align-items-center" href="{% url 'user_profile_update' user.pk %}">
                   {% if user.image %}
                    <img src="{{ user.image.url}}?v={{ user.pk }}" alt="" width="50" height="40" class="rounded align-middle">
                       {% else %}
                       <img src="{% static 'images/default.jpeg' %}" alt="" width="50" height="40" class="rounded align-middle">
                   {% endif %}
                <span class="ms-2">{{ user.first_name }}</span>
            </a>

                {% else %}
              {% endif %}
              <ul class="nav nav-pills">

          <li class="nav-link enable">
              {% if user.is_authenticated %}
                  <a class="btn btn-danger" href="{% url 'logout' %}">Выйти</a>
              {% else %}
              <a class="nav-link active" href="{% url 'login' %}">Войти</a>
                  <li class="nav-link enable">
                      <a class="nav-link active" href="{% url 'register' %}">Регистрация</a>
            </li>
              {% endif %}
          </li>
              </ul>
    </ul>
  </div>
</nav>

    {% block content %}
    {% endblock %}
<footer class="bg-secondary text-white sticky-bottom py-2 mt-4">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p class="lead text-center text-light">ОшГУ - 2023</p>
      </div>
    </div>
  </div>
</footer>
    </body>
    </html>

templates/estate_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h1>Добавить объявление</h1>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
          {{ formset.management_form }}
          <script type="text/html" id="images-template">
                <tr id="images-__prefix__" class= hide_all>
                    {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                    {% endfor %}

                    {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                    {% endfor %}
                </tr>
          </script>
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Добавить изображение</h4>
            </div>
            <table class="table card-body">
                <thead class="text-secondary">
                <th>Изображение <span style="color: red;" class="required">*</span></th>
                <th></th>
                <th>Кнопка удаления</th>
                </thead>
                <tbody id="item-images">
                {% for error in formset.non_form_errors %}
                <span style="color: red">{{ error }}</span>
                {% endfor %}
                {% for forms in formset %}
                {{ forms.management_form }}
                <tr id="images-{{ forloop.counter0 }}" class= hide_all>
                    {{ forms.id }}
                    {% for field in forms.visible_fields %}
                    <td>
                        {{field}}
                        {% for error in field.errors %}
                        <span style="color: red">{{ error }}</span>
                        {% endfor %}
                    </td>
                    {% endfor %}
                    {% if forms.instance.pk %}
                    <td>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{forms.instance.pk}}">
                            Удалить
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal{{forms.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{forms.instance.pk}}" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel{{forms.instance.pk}}">Вы точно хотите удалить запись?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{% url 'image_delete' forms.instance.pk %}" type="button" class="btn btn-primary">Да, удалить</a>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <button type="button" id="add-page-button" class="btn btn-secondary add-images">Добавить</button>
        </div>
        <h1></h1>
        <div class="form-group">
            <button type="submit" class="btn btn-secondary btn-block">Сохранить</button>
        </div>
      </form>

<script type="text/javascript">
        $(document).ready(function() {
          $('.add-images').click(function(ev) {
              ev.preventDefault();
              var count = $('#item-images').children().length;
              var tmplMarkup = $('#images-template').html();
              var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
              $('#item-images').append(compiledTmpl);

              // update form count
              $('#id_images-TOTAL_FORMS').attr('value', count+1);
          });

        $("input#id_images").on('change', function() {
        var formset_inputs = $('div.table-responsive.card.mt-4').find('button,input');
        console.log(formset_inputs);
        var status = Boolean($(this).val());
        console.log(status);
        console.log(formset_inputs.length);
        for(let i=0; i < formset_inputs.length; i++) {
            console.log(formset_inputs[i]);
            $(formset_inputs[i]).prop('disabled', status);
        };
        });
        });
    </script>

{% endblock %}

templates/estate_detail.html
{% extends 'base.html' %}

{% block content %}
    <hr>
<div class="row">
    <div class="card">
      <div class="card-body">
          <div class="col-sm-6 mb-3 mb-sm-0">
          <div id="carouselID" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{ estate.images.all.first.image.url }}" class="d-block w-100" style="width: 100% !important; height: 75vh;" alt="...">
            </div>
              {% for image in estate.images.all|slice:"1:" %}
                <div class="carousel-item">
                  <img src="{{ image.image.url }}" class="d-block w-100" style="width: 100% !important; height: 75vh;" alt="...">
                </div>
              {% endfor %}
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselID" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselID" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
            </div>
              <div class="col-sm-6 mb-3 mb-sm-0">
              <h5 class="card-title">{{ estate.name }}</h5>
              <p class="card-text">{{ estate.description }}</p>
              <ul>
                <li>Площадь участка: {{ estate.plot_area }}</li>
                <li>Площадь дома: {{ estate.house_area }}</li>
                <li>Тип сделки: {{ estate.get_deal_type_display }}</li>
                <li>Цена: {{ estate.price }} {{ estate.get_currency_display }}</li>
                <li>Телефон: {{ estate.phone }}</li>
                <li>Расположение: {{ estate.location }}</li>
                <li>Целевое назначение: {{ estate.target }}</li>
                <li>Документы: {{ estate.documents }}</li>
                <li>
                    Коммуникации:
                    {% for elem in estate.communications.all %}
                    {{ elem }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </li>
                <li>
                    Инфраструктура:
                    {% for elem in estate.infrastructure.all %}
                    {{ elem }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </li>
                <li>Тип оплаты: {{ estate.payment_term }}</li>
              </ul>
        <a href="{% url 'estate_update' estate.pk %}" class="btn btn-primary mt-3">Редактировать</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/estate_list.html
<style>
.card-title {
  height: 3rem;
}
.card-text {
  height: 3rem;
  overflow: hidden;
}
</style>

{% extends 'base.html' %}
{% block content %}
  <div class="container mt-4">
    <h1 class="mt-3">Список недвижимости</h1>
    <hr>
{#    <div class="row row-cols-1 row-cols-md-4 g-4">#}
  <div class="row row-cols-4 g-4">
      {% for estate in estates %}
        <div class="col">
          <div class="d-inline-flex p-2">
              <div class="card-header">
              <img src="{{ estate.images.all.first.image.url }}" class="card-img-top" alt="{{ estate.name }}" height="200px">
<!--                  <img src="{{ estate.image.url }}" class="card-img-top" alt="{{ estate.name }}" height="200px">-->
            <div class="card-body">
              <h5 class="card-title">{{ estate.name }}</h5>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Тип сделки: {{ estate.get_deal_type_display }}</li>
                <li class="list-group-item">Цена: {{ estate.price }} {{ estate.get_currency_display }}</li>
                <li class="list-group-item">Телефон: {{ estate.phone }}</li>
                <li class="list-group-item">Расположение: {{ estate.location }}</li>
              </ul>
              <a href="{% url 'estate_detail' estate.pk %}" class="btn btn-primary mt-3">Подробнее</a>
            </div>
          </div>
          </div>
        </div>

      {% empty %}
        <p>Нет доступных объектов недвижимости.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/estate_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h1>Редактировать объявление</h1>
  <form method="post" action="{% url 'estate_update' estate.pk %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy}}
     <button type="submit" class="btn btn-primary">Сохранить</button>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal">
      Удалить
    </button>
</form>
    <!-- Modal -->
    <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="delete-modal-label">Подтвердите удаление</h5>
            <button type="button" class="btn-close" data-dismiss="modal" aria-label="Закрыть">
            </button>
          </div>
          <div class="modal-body">
            Вы уверены, что хотите удалить это объявление?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Отмена</button>
            <form method="post" action="{% url 'estate_delete' estate.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Удалить</button>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h1>Редактирование профиля</h1>
  <form method="post" action="{% url 'user_profile_update' user.pk %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy}}
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
{% endblock %}